export const MOCK_DATA = {
    mentor: {
        name: 'Victor Lal',
        title: 'Founder at TechCo',
        avatar: '/assets/victor.png',
        company: 'TechCo',
    },
    mentee: {
        name: 'Sarah Chen',
        title: 'Product Manager',
        avatar: 'https://i.pravatar.cc/150?u=sarah',
    },
    aiBrief: [
        'Both focused on early-stage SaaS growth strategies',
        'Victor has scaled 2 companies past Series A',
        'Your product-market fit questions align with his expertise',
        'Shared interest in developer-focused go-to-market',
    ],
    dates: [
        { id: 'd1', label: 'Mon', date: '12', full: 'Monday, Jan 12' },
        { id: 'd2', label: 'Tue', date: '13', full: 'Tuesday, Jan 13' },
        { id: 'd3', label: 'Wed', date: '14', full: 'Wednesday, Jan 14' },
        { id: 'd4', label: 'Thu', date: '15', full: 'Thursday, Jan 15' },
        { id: 'd5', label: 'Fri', date: '16', full: 'Friday, Jan 16' },
        { id: 'd6', label: 'Sat', date: '17', full: 'Saturday, Jan 17' },
        { id: 'd7', label: 'Sun', date: '18', full: 'Sunday, Jan 18' },
        { id: 'd8', label: 'Mon', date: '19', full: 'Monday, Jan 19' },
        { id: 'd9', label: 'Tue', date: '20', full: 'Tuesday, Jan 20' },
        { id: 'd10', label: 'Wed', date: '21', full: 'Wednesday, Jan 21' },
        { id: 'd11', label: 'Thu', date: '22', full: 'Thursday, Jan 22' },
        { id: 'd12', label: 'Fri', date: '23', full: 'Friday, Jan 23' },
        { id: 'd13', label: 'Sat', date: '24', full: 'Saturday, Jan 24' },
        { id: 'd14', label: 'Sun', date: '25', full: 'Sunday, Jan 25' },
    ],
    times: [
        { id: 't1', label: '9:00 AM' },
        { id: 't2', label: '10:30 AM' },
        { id: 't3', label: '1:00 PM' },
        { id: 't4', label: '2:30 PM' },
        { id: 't5', label: '4:00 PM' },
    ],
    timesLeft: [
        { id: 'tl1', label: '8:00am' },
        { id: 'tl2', label: '9:00am' },
        { id: 'tl3', label: '11:00am' },
        { id: 'tl4', label: '12:00pm' },
        { id: 'tl5', label: '1:00pm' },
        { id: 'tl6', label: '4:00pm' },
        { id: 'tl7', label: '5:00pm' },
        { id: 'tl8', label: '6:00pm' },
    ],
    timesRight: [
        { id: 'tr1', label: '8:30am' },
        { id: 'tr2', label: '9:30am' },
        { id: 'tr3', label: '11:30am' },
        { id: 'tr4', label: '12:30pm' },
        { id: 'tr5', label: '1:30pm' },
        { id: 'tr6', label: '4:30pm' },
        { id: 'tr7', label: '5:30pm' },
        { id: 'tr8', label: '6:30pm' },
    ],
    initialSuggestions: [
        'Looking forward to it! 👋',
        'See you Thursday!',
        "Can't wait to connect!",
    ],
    mentorReplies: ['Likewise!', 'Me too! 😊', 'See you then!'],
}
